// <auto-generated />
using FeWoVerwaltung.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeWoVerwaltung.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250611115145_mig01")]
    partial class mig01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FeWoVerwaltung.Model.Buchung", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte>("AnzahlPersonen")
                        .HasColumnType("tinyint");

                    b.Property<long>("FeWoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Inaktiv")
                        .HasColumnType("bit");

                    b.Property<byte>("Kalenderwoche")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FeWoId");

                    b.ToTable("Buchungen");
                });

            modelBuilder.Entity("FeWoVerwaltung.Model.FeWo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Inaktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreisProWoche")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FeWos");
                });

            modelBuilder.Entity("FeWoVerwaltung.Model.Buchung", b =>
                {
                    b.HasOne("FeWoVerwaltung.Model.FeWo", "FeWo")
                        .WithMany()
                        .HasForeignKey("FeWoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeWo");
                });
#pragma warning restore 612, 618
        }
    }
}
